### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by andygrunwald** [a-h/generate#14]
I try to compile this schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "name": "Repository Configuration",
    "type": "object",
    "additionalProperties": false,
    "required": [ "name" ],
    "properties": {
        "name": {
            "type": "string",
            "description": "Repository name."
        },
        "repositories": {
            "type": "array",
            "description": "A set of additional repositories where packages can be found.",
            "additionalProperties": true
        }
    }
}

```

via

```sh
$ go run main.go -i satis/res/satis-schema.json
```

and i got:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6c98b]

goroutine 1 [running]:
panic(0xd2d00, 0xc420012090)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
github.com/a-h/generate/jsonschema.addTypeAndChildrenToMap(0xc420012cb0, 0xc, 0xc420012710, 0xc, 0xc420096800, 0xc42000a720)
	/.../Development/Go/src/github.com/a-h/generate/jsonschema/jsonschema.go:53 +0x52b
github.com/a-h/generate/jsonschema.addTypeAndChildrenToMap(0xed171, 0x1, 0x0, 0x0, 0xc420096000, 0xc42000a720)
	/.../Development/Go/src/github.com/a-h/generate/jsonschema/jsonschema.go:84 +0x212
github.com/a-h/generate/jsonschema.(*Schema).ExtractTypes(0xc420096000, 0x0)
	/.../Development/Go/src/github.com/a-h/generate/jsonschema/jsonschema.go:42 +0x90
github.com/a-h/generate.(*Generator).CreateStructs(0xc420041e70, 0x2d9b, 0xc420096000, 0x0)
	/.../Development/Go/src/github.com/a-h/generate/generator.go:31 +0x99
main.main()
	/.../Development/Go/src/github.com/a-h/generate/cmd/schema-generate/main.go:40 +0x315
exit status 2
```

**Comment by a-h** [comment]
Thanks Andy, the issue was that `generate` expected the items element of the array definition to have data in it. I fixed it in #19 by defaulting to []interface{} if there is no definition for the type of the array items.
